apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: default-kv
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: replaced-by-kustomize
      serviceAccountRef:
        name: cluster-secret-store-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  # this service account was created by azwi
  name: cluster-secret-store-sa
  annotations:
    test: replace-by-kustomize
    azure.workload.identity/client-id: replaced-by-kustomize
    azure.workload.identity/tenant-id: 25c1df4b-00ea-4e39-98bd-5f1143c5c5df
    argocd.argoproj.io/sync-wave: "5"
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-external-secrets-operator
  namespace: operators
spec:
  channel: alpha
  name: external-secrets-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
---
apiVersion: operator.external-secrets.io/v1alpha1
kind: OperatorConfig
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true # Since this is a CRD created by the above subscription
spec:
  crds:
    createClusterSecretStore: true
  prometheus:
    enabled: true
    service:
      port: 8080
  resources:
    requests:
      cpu: 10m
      memory: 96Mi
    limits:
      cpu: 100m
      memory: 256Mi
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: default-kv
  target:
    name: test-secret
    creationPolicy: Owner
  data:
  # name of the SECRET in the Azure KV (no prefix is by default a SECRET)
  - secretKey: database-username
    remoteRef:
      key: AllowSpecificOriginsURL
