apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-secrets.yaml
patches:
  - target:
      kind: ServiceAccount
      name: cluster-secret-store-sa
    patch: |-
      - op: replace
        path: "/metadata/annotations/azure.workload.identity~1client-id"
        value: inserted-by-kustomize
