apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: external-secrets
  namespace: argocd
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  roles:
    # A role which provides read-only access to all applications in the project
    - name: admin
      description: admin privileges over external-secrets
      policies:
        - p, proj:external-secrets:admin, applications, create, external-secrets/*, allow
        - p, proj:external-secrets:admin, applications, delete, external-secrets/*, allow
        - p, proj:external-secrets:admin, applications, get, external-secrets/*, allow
        - p, proj:external-secrets:admin, applications, override, external-secrets/*, allow
        - p, proj:external-secrets:admin, applications, sync, external-secrets/*, allow
        - p, proj:external-secrets:admin, applications, update, external-secrets/*, allow
        - p, proj:external-secrets:admin, logs, get, external-secrets/*, allow
        - p, proj:external-secrets:admin, exec, create, external-secrets/*, allow
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nelsontest
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - env: shared-uat
            userAssignedIdentityID: 26c55287-e582-49c7-87ab-17ce18b60ef9
            server: https://kubernetes.default.svc
            kv: kvaksuateus201
  template:
    metadata:
      name: external-secrets-{{.env}}
    spec:
      project: external-secrets
      source:
        path: other/external-secrets/overlays
        repoURL: https://github.com/NelsonG6/argo-issue.git
        kustomize:
          patches:
            - target:
                kind: ClusterSecretStore
                name: default-kv
              patch: |-
                - op: replace
                  path: /spec/provider/azurekv/vaultUrl
                  value: https://{{.kv}}.vault.azure.net
            - target:
                kind: ServiceAccount
                name: cluster-secret-store-sa
              patch: |-
                - op: replace
                  path: "/metadata/annotations/azure.workload.identity~1client-id"
                  value: "{{.userAssignedIdentityID}}"
      destination:
        server: "{{.server}}"
        namespace: external-secrets
      syncPolicy:
        # automated:
        #   selfHeal: true
        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=true
---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: external-secrets-test
# spec:
#   project: external-secrets
#   source:
#     path: other/external-secrets
#     repoURL: https://github.com/r1-development/scf-aks-argocd/
#     kustomize:
#       patches:
#         - target:
#             kind: ClusterSecretStore
#             name: default-kv
#           patch: |-
#             - op: replace
#               path: /spec/provider/azurekv/vaultUrl
#               value: https://test.vault.azure.net
#         - target:
#             kind: ServiceAccount
#             name: workload-identity-sa
#           patch: |-
#             - op: replace
#               path: "/metadata/annotations/azure.workload.identity~1client-id"
#               value: "{{.userAssignedIdentityID}}"
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: external-secrets
#   syncPolicy:
#     syncOptions:
#       - ServerSideApply=true
#       - CreateNamespace=true
